
def story1():
    global name
    print("\033c", end="")
    print("$%^&: A human will often make irrational dicisions, even in doubt they will continue")
    input()
    print("$%^&: When a person doesnt know what to do, they choose to stop thinking, set their mind on a specific goal and dont sway from it")
    input()
    print("$%^&: In the end humans have a fragile mind")
    input()
    print("\033c", end="")
    print("A grass hill. That is what you see as you wake up from a mid-day nap")
    input()
    print("You still feel a little sleepy as the wind blows")
    input()
    print("?: Oh, you final woke up...")
    input()
    print("You look over to see a man fully clad in armour sitting next to you")
    input()
    print("?: Oh sorry, I should introduce myself. My name is Adel. Dont mind me, I just like this spot as well")
    input()
    print("Adel: How may I call you?")
    input()
    print("You dont remember how you much about how you got here or why youre here, you dont have any memories about your life before you came to this place, but you do remember your name")
    input()
    name = input("My name is: ")
    input()
    print("\033c", end="")
    print("Adel: Hmm, ok then " + str(name) + "how about you tell me more ab...")
    input()
    print("As the two of you are talking you hear something walking through the grass...")
    input()
    print("\033c", end="")
    print("A golbin appears")
    input()
    print("however Adel doesnt seem fazed")
    input()
    print("Adel: Here catch")
    input()
    print("\033c", end="")
    print("Sword has been added to Inventory")
    input()
    print("\033c", end="")
    print("The goblin has come too close to run away")
    print("\033c", end="")

def story2():
    print("\033c", end="")
    print("Adel: well that was something...")
    input()
    print("random soldier: Captain, we need to keep going!")
    input()
    print("Adel: Aw shit, have to get going...")
    input()
    print("Adel: Have a nice day!")
    input()
    print("Adel: And btw, you can keep the sword.")
    input()
    print("Adel: The most nearby city is to the south")
    input()
    print("\033c", end="")
    print("Adel walks away and you decide to follow his advice and go to south")
    input()
    print("As youre walking you see a vilage, with a crippled man sitting just outside")
    input()
    print("\033c", end="")
    print("Villager: I wouldnt go in there if I were you.")
    input()
    print("Villager: The village is done for")
    input()
    print("Villager: the plague has already consumed this place")


def plg1():
    print("\033c", end="")
    print("Villager: What a naive person")
    input()
    print("\033c", end="")
    print("As you walk you can see dead bodies on the streets")
    input()
    print("Anyone that is alive is more akin to a skin and bones, somehow still moving")
    input()
    print("As you walk you see a big pile of bodies and feel a tap on your shoulder ...")
    input()
    print("You see a squad of men in plague doctor masks, some of them holding staffs")
    input()
    print("\033c", end="")
    print("Doctor: You dont seem to be from around here... Step back or even better get out of here while youre not suffering on the ground")
    input()
    print("Doctor: And oh yea, before you catch the decease")
    input()
    print("\033c", end="")
    print("The Doctor holds his hand in front of you")
    input()
    print("His hand starts to glow faintly")
    input()
    print("\033c", end="")
    print("Doctor: that should do")
    input()
    print("Doctor: Now scram")
    input()
    print("\033c", end="")
    print("??: Hey, you...")
    input()
    print("??: Mind helping me lad?")
    input()
    print("\033c", end="")
    print("you look the way where the sound came from and you see a man, barely breathing")
    input()
    print("Man: It looks like the end of the road for me, could you help me get to my mother")
    input()

def plg2():
    print("Man: Thank you")
    input()
    print("\033c", end="")
    print("you help him walk to an isolated house, as you enter you hear a faint voice")
    input()
    print("\033c", end="")
    print("Victor?")
    input()
    print("Man: Yes mother, its me, im home")
    input()
    print("Victor: Thank you, I will be fine now.")
    input()
    print("As for your reward, look in that locker")
    input()
    print("\033c", end="")
    print("Victor walks over to the bed on which his mother lies")
    input()
    print("As he sits down with a groun he says")
    input()
    print("Victor: you may take whatever you like, I wont be sticking around anyway")
    input()
    print("\033c", end="")
    print("A second later neither the man nor the mother were breathing")
